### ISSUE TITLE
求推荐一个IDE

### ISSUE THREAD

**Issue by leveryd2** [hoohack/read-php-src#4]
我用clion看5.6的源码，发现很多函数不能跳到定义。比如看strpos函数的实现时，php_memnstr函数不能跳到定义部分。

**Comment by ivar66** [comment]
you can use phpstorm or zendstudio

**Comment by hoohack** [comment]
我是用vim+ctags，你也可以试试sublime text + ctags@leveryd2

**Comment by septnn** [comment]
sublime text + ctags

**Comment by leveryd2** [comment]
最终还是用clion搭建的调试环境
参考 [clion调试php扩展](https://blog.csdn.net/baixiaoshi/article/details/73744280)搭建也很方便
